### ISSUE TITLE
Change API interface to accept Base64URL encoded hash instead of Base58

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree-ipfs#12]

**Comment by sylar217** [comment]
The PR is merged, if there is nothing left in the issue, lets close it?

**Comment by thehenrytsai** [comment]
Sounds good, code committed at: https://github.com/decentralized-identity/sidetree-ipfs/commit/615bcd884ebd5f5c1fd37c136e0cc34968466109
