### ISSUE TITLE
Upgrade IPFS version to 0.34

### ISSUE THREAD

**Issue by sylar217** [decentralized-identity/sidetree-ipfs#17]
Upgrade to JS IPFS version to 0.34 and change the default encoding of IPFS to use base 64 and address file API changes.

**Comment by thehenrytsai** [comment]
I thought I have changed the interface encoding to Base64URL already in https://github.com/decentralized-identity/sidetree-ipfs/commit/615bcd884ebd5f5c1fd37c136e0cc34968466109?

**Comment by sylar217** [comment]
The new IPFS version has some api changes and provides the option for using base64 out of the box instead of writing a separate interface.

**Comment by thehenrytsai** [comment]
Make sure that the encoding supported is Base64URL, not just Base64.

**Comment by sylar217** [comment]
https://github.com/ipfs/js-ipfs/releases/tag/v0.34.0 , is released, now we can upgrade too.

**Comment by vihanda** [comment]
Upgraded the IPFS version to 0.34. PR raised.

**Comment by sylar217** [comment]
PR merged
