### ISSUE TITLE
Fix 2 low severity vulnerabilities.

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree-ipfs#18]
=== npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  Low             Prototype Pollution

  Package         lodash

  Patched in      >=4.17.5

  Dependency of   ipfs

  Path            ipfs > ipld-zcash > zcash-bitcore-lib > lodash

  More info       https://nodesecurity.io/advisories/577

  Low             Prototype pollution

  Package         merge-recursive

  Patched in      No patch available

  Dependency of   ipfs

  Path            ipfs > libp2p-websocket-star > merge-recursive

  More info       https://nodesecurity.io/advisories/715

found 2 low severity vulnerabilities in 18248 scanned packages
  2 vulnerabilities require manual review. See the full report for details.

**Comment by sylar217** [comment]
This should get addressed, after we upgrade IPFS to 0.34
