### ISSUE TITLE
Unable to run Sidtree IPFS node from master

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree-ipfs#19]
Got the following error when attempting to run the IPFS mode from `master`:

D:\sidetree-ipfs>npm start

> sidetree-ipfs@0.1.0 start D:\sidetree-ipfs
> node dist/src/index.js

Sidetree-IPFS node running on port: 3001
(node:11352) UnhandledPromiseRejectionWarning: Error: Lock file is already being hold
    at options.fs.mkdir (D:\sidetree-ipfs\node_modules\proper-lockfile\lib\lockfile.js:39:43)
    at FSReqWrap.oncomplete (fs.js:141:20)
(node:11352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sylar217** [comment]
This is happening because of the content is being stored in the same folder which has a lock file to prevent multiple ipfs nodes to use it. Deleting the sidetree_ipfs folder where content is stored will resolve this. Need to address this as part of how to re-use the existing content stored in the repo after a crash/restart

**Comment by thehenrytsai** [comment]
Thanks @sylar217 for the explanation, feel free to change the title to reflect the issue better.

**Comment by sylar217** [comment]
Was happening in some version of ipfs-repo, when the nodejs process gets killed abrubtly and the ipfs node isnt able to remove the lock. Will raise a PR to handle this gracefully

**Comment by sylar217** [comment]
Addressed in https://github.com/decentralized-identity/sidetree-ipfs/pull/25
