### ISSUE TITLE
Sidetree IPFS node, can be queried only via the exposed API, not via the IPFS gateway or API

### ISSUE THREAD

**Issue by sylar217** [decentralized-identity/sidetree-ipfs#7]
The machine that spawns the sidetree-ipfs node: 

- Shouldn't allow other users to pin content to this node via IPFS api's. 
- This node should only store sidetree related content, and nothing else.

**Comment by thehenrytsai** [comment]
@sylar217, I am closing this issue since you've verified that the above statements are true. Let me know if it is otherwise.
